apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: ${POOL_NAME}
spec:
  selector:
    matchLabels:
      app: ${POOL_NAME}
  endpointPickerRef:
    name: ${PROXY_NAME}
    kind: Service
    port:
      number: 9002
  targetPorts:
  - number: ${TARGET_PORTS}
