apiVersion: v1
kind: Service
metadata:
  name: ${PROXY_NAME}
spec:
  type: NodePort
  selector:
    app: ${PROXY_NAME}
  ports:
  - name: default
    protocol: TCP
    port: 9002
    targetPort: 9002
    appProtocol: http
    nodePort: 30080
  - name: zmq
    protocol: TCP
    port: 5557
    targetPort: 5557
    appProtocol: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: ${PROXY_NAME}-zmq
spec:
  type: ClusterIP
  selector:
    app: ${PROXY_NAME}
  ports:
  - name: zmq
    protocol: TCP
    port: 5557
    targetPort: 5557
    appProtocol: tcp